#!/usr/bin/env bash

export BUN_PATH="${BUN_PATH:-${HOME}/.bun}"

if [ -d "${BUN_PATH}" ]; then
  export PATH="${PATH:+${PATH}:}${HOME}/.bun/bin"

  case $SHELL in
  */zsh)
    if [ ! -s "${BUN_PATH}/_bun.zsh" ]; then
      curl -fsSL https://raw.githubusercontent.com/oven-sh/bun/HEAD/completions/bun.zsh >"${BUN_PATH}/_bun.zsh"
    fi
    . "${BUN_PATH}/_bun.zsh"
    ;;

  */bash)
    if [ ! -s "${BUN_PATH}/_bun.bash" ]; then
      curl -fsSL https://raw.githubusercontent.com/oven-sh/bun/HEAD/completions/bun.bash >"${BUN_PATH}/_bun.bash"
    fi
    . "${BUN_PATH}/_bun.bash"
    ;;

  */fish)

    if [ ! -s "${BUN_PATH}/_bun.fish" ]; then
      curl -fsSL https://raw.githubusercontent.com/oven-sh/bun/HEAD/completions/bun.fish >"${BUN_PATH}/_bun.fish"
    fi
    . "${BUN_PATH}/_bun.fish"
    ;;
  esac
fi

# export PATH="${PATH:+${PATH}:}$HOME/.bun/bin:$HOME/bin"
# PATH="${PATH:+${PATH}:}$HOME/bin" DOTLY_INSTALL=true DOTFILES_PATH="${HOME}/.dotfiles" SLOTH_PATH="${HOME}/.dotfiles/modules/sloth" "${HOME}/.dotfiles/modules/sloth/bin/dot"
