#!/usr/bin/env bash

export BUN_PATH="${BUN_PATH:-${HOME}/.bun}"

if [ -s "${BUN_PATH}/_bun" ]; then
  export PATH="${PATH:+${PATH}:}${HOME}/.bun/bin"
  #shellcheck disable=SC1091
  . "${BUN_PATH}/_bun"
fi

# export PATH="${PATH:+${PATH}:}$HOME/.bun/bin:$HOME/bin"
# PATH="${PATH:+${PATH}:}$HOME/bin" DOTLY_INSTALL=true DOTFILES_PATH="${HOME}/.dotfiles" SLOTH_PATH="${HOME}/.dotfiles/modules/sloth" "${HOME}/.dotfiles/modules/sloth/bin/dot"
