#!/usr/bin/env bash

# In my case I want to setup directly "$HOME/.nvm"
#export NVM_DIR=[ -n $(brew --prefix nvm) ] && $(brew --prefix nvm) || "$HOME/.nvm"
export NVM_DIR="$HOME/.nvm"
# This loads nvm bash_completion which is bash and zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

nvm() {
  unset -f nvm node npm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
  nvm "$@"
}
node() {
  unset -f nvm node npm
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
  node "$@"
}
npm() {
  unset -f nvm node npm
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
  npm "$@"
}
