#!/usr/bin/env bash

export NVM_DIR="$HOME/.nvm"
#shellcheck source=/dev/null
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

if [[ "${SHELL##*/}" == "bash" ]]; then
  #shellcheck source=/dev/null
  [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" # This loads nvm bash_completion
fi
