#!/usr/bin/env bash
##? Prune all docker stuff
#?? 1.0.0
##?
##? Usage:
##?   prune [-f | --force]

if ! ${force:-false}; then
  output::yesno "Do you want to prune all docker stuff? This will include, containers, images, volumes, networks, etc."
fi

docker container prune --force
docker volume prune --force
docker network prune --force
docker system prune -a --force
