#!/usr/bin/env bash
set -eo pipefail

. "$DOTLY_PATH/scripts/core/_main.sh"

##? Downloads a video in the current directory
##?
##? Usage:
##?   download-mp4 <url>
docs::parse "$@"

[[ -n "${url:-}" ]] && youtube-dl --format mp4 "${url}"
