#!/usr/bin/env bash

set -euo pipefail

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"

##? Send a local notification
##? 
##?
##? Usage:
##?   local_notification [-h | --help]
##?   local_notification [-v | --version]
##?   local_notification <title> <body>...
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot utils local_notification"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

[[ -z "${title:-}" ]] && exit 1

os="$(uname)"
if [[ "$os" == "Darwin" ]]; then
  osascript -e 'display notification "'"${body[*]:-}"'" with title "'"${title}"'"' 
fi
