#!/usr/bin/env bash

set -euo pipefail

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"

##? Convert a test as binary representation
##? 
##?
##? Usage:
##?   asBinary [-h | --help]
##?   asBinary [-v | --version]
##?   asBinary <text>...
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot text asBinary"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

binary_text="$(echo "${text[*]:-}" | perl -lpe '$_=unpack"B*"')"

for (( i=0; i < ${#binary_text}; i++ )); do
  if [[ $(( i % 8 )) == 0 ]] && [ $i != 0 ]; then
    echo -n " "
  fi

  echo -n "${binary_text:$i:1}"
done