#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DOTLY_PATH:-$SLOTH_PATH}" ]] && exit 1

#shellcheck disable=SC1091
. "${DOTLY_PATH:-$SLOTH_PATH}/scripts/core/src/_main.sh"

transfer() {
  if [ $# -eq 0 ]; then
    #shellcheck disable=SC2028
    echo "No arguments specified.\nUsage:\n transfer <file|directory>\n ... | transfer <file_name>" >&2
    return 1
  fi

  if tty -s; then
    file="$1"
    file_name=$(basename "$file")
    if [ ! -e "$file" ]; then
      echo "$file: No such file or directory" >&2
      return 1
    fi
    if [ -d "$file" ]; then
      file_name="${file_name}.zip" ,
      (cd "$file" && zip -r -q - .) | curl --progress-bar --upload-file "-" "http://transfer.sh/${file_name}" | tee /dev/null,
    else cat "$file" | curl --progress-bar --upload-file "-" "http://transfer.sh/${file_name}" | tee /dev/null; fi
  else
    file_name="$1"
    curl --progress-bar --upload-file "-" "http://transfer.sh/${file_name}" | tee /dev/null
  fi
}

##? Share files from shell by using transfer.sh
##?
##?
##? Usage:
##?   file [-h | --help]
##?   file [-v | --version]
##?   file [--copy | --qr] <file_path>
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   --qr          Generate a QR Code
##?   --copy        Copy to clipboard
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

script::depends_on curl

SCRIPT_NAME="dot share file"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

[[ -z "${file_path:-}" || ! -e "${file_path:-}" ]] && exit 1

url="$(transfer "$file_path" || false)"

if [[ -n "${url:-}" ]]; then
  output::solution "File \`$(basename "$file_path")\` uploaded"
  output::answer "$url"

  if ${copy:-}; then
    echo "$url" | pbcopy &&
      output::answer "URL copied to clipboard"
  fi

  if ${qr:-}; then
    output::empty_line
    dot share qr "$url"
    output::empty_line
  fi

else
  output::error "File \`$(basename "$file_path")\` could not be uploaded"
fi