#!/usr/bin/env bash

# TODO

set -euo pipefail

[[ -z "${SLOTH_PATH:-${DOTLY_PATH:-}}" ]] && exit 1

#shellcheck disable=SC1091
. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"

##? Make a StreamDeck Backup
##?
##?
##? Usage:
##?   mac_backup [-h | --help]
##?   mac_backup [-v | --version]
##?   mac_backup <path_to_backup>
##?
##? Arguments:
##?   <path_to_backup>  Directory Path were to place the backup of your current StreamDeck configuration
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot streamdeck mac_backup"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

STREAMDECK_PATH="$HOME/Library/Application Support/com.elgato.StreamDeck/ProfilesV2"

TIME=$(date +%s)
FILENAME="StreamDeckProfiles-${TIME}.tar.bz2"

tar --create --bzip2 --file "${SAVE_DIR}/${FILENAME}" "$CONFIG_DIR:t"

# check to see if 'tar' reported success
EXIT="$?"
