#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
. "$DOTLY_PATH/scripts/core/_main.sh"

##?   Executes a script from remote url
##?
##? Usage:
##?   remote_bash <url>
docs::parse "$@"

[[ -z "${url:-}" ]] && exit 1

bash <(curl -fsL "$url")
