#!/usr/bin/env bash

set -euo pipefail

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
dot::load_library "ha.sh"

##? Execute Hassio Service from console
##?
##?
##? Usage:
##?   service [-h | --help]
##?   service [-v | --version]
##?   service <domain> [<json>]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot ha service"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

url="$HASS_API_URL/services"

if [[ -n "${json:-}" ]]; then
  curl --silent -X POST -H "Content-Type: application/json" \
    -H "Authorization: Bearer $HASS_TOKEN" \
    -d "$json" \
    "$url/$(echo "$domain" | tr "." "/")"
else
  output="$(curl --silent -X GET -H "Content-Type: application/json" \
    -H "Authorization: Bearer $HASS_TOKEN" \
    "$url")"

  if [[ -n "${domain:-}" ]]; then
    echo "$output" | jq -r --arg domain "$domain" '.[] | select(.domain == $domain) | .'
  else
    echo "$output"
  fi
fi
