#!/usr/bin/env bash

set -euo pipefail

[[ -z "$DOTLY_PATH" ]] && exit 1

#shellcheck source=/dev/null
. "$DOTLY_PATH/scripts/core/_main.sh"

##? Show used network ports and the application that is using it
##? 
##?
##? Usage:
##?   netports [-h | --help]
##?   netports [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot system netports"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi
netstat -Watnlv | grep LISTEN | awk '{"ps -o comm= -p " $9 | getline procname; print $1 " | " $4 " |  " $9 " | " procname;  }' | column -t -s '|'
