#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DOTLY_PATH:-$SLOTH_PATH}" ]] && exit 1

#shellcheck disable=SC1091
. "${DOTLY_PATH:-$SLOTH_PATH}/scripts/core/src/_main.sh"

script::depends_on catimg jq curl

##?
##?
##?
##? Usage:
##?   random [-h | --help]
##?   random [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot cat random"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

RANDOM_CAT_URL="$(curl --silent "http://aws.random.cat/meow" | jq -r '.file')"
FILE_OUTPUT="$(mktemp)"
curl --silent "$RANDOM_CAT_URL" --output "$FILE_OUTPUT"

[[ -f "$FILE_OUTPUT" ]] && catimg -w 200 -l 0 "$FILE_OUTPUT"
output::write "\`$RANDOM_CAT_URL\`"
output::answer "Using: http://aws.random.cat/meow"
rm -rf "$FILE_OUTPUT"
