#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Print command after unifi-os shell for udm-p install command
##?
##? Usage:
##?    install-command <pkg_url>
docs::parse "$@"

if [[ ! -z "$pkg_url" ]]; then
  echo "rm \"/tmp/unifi_sysvinit_all.deb\" &> /dev/null; curl -o \"/tmp/unifi_sysvinit_all.deb\" \"$pkg_url\" && dpkg -i \"/tmp/unifi_sysvinit_all.deb\" && rm \"/tmp/unifi_sysvinit_all.deb\""
else
  echo "Not url provided"
fi
