#!/usr/bin/env bash
##? Flash by using wally-cli a keyboard
##?
##?
##? Usage:
##?   flash [-h | --help]
##?   flash [-v | --version]
##?   flash [--open] [<id> [<kbversion>]]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   --open        Open keyboard id with `open` command, so must open in the browser.
##?   <id>          Keyboard id, if not defined try to use ZSA_KEYBOARD_ID if defined
##?   <version>     Keyboard version, if not defined use latest
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
#? v1.2.0

keyboard_id="${id:-${ZSA_KEYBOARD_ID:-}}"
if [[ -z "${keyboard_id:-}" ]]; then
  output::error "\`ZSA_KEYBOARD\` is not set"
  exit 1
fi

zsa_url() {
  # latest can be replaced by a specific version
  # ZSA_URL="https://oryx.zsa.io/{layout ID}/latest/binary"
  printf "https://oryx.zsa.io/%s/%s/binary" "${1:-}" "${2:-latest}"
}

if ${open:-false}; then
  open "$(printf "https://configure.zsa.io/moonlander/layouts/%s/%s" "${keyboard_id}" "${kbversion:-latest}")"
  exit
fi

tmp_file="$(mktemp)"
mv "${tmp_file}" "${tmp_file}.bin"
tmp_file="${tmp_file}.bin"
if ! curl -sfL "$(zsa_url "${keyboard_id}" "${kbversion:-latest}")" -o "${tmp_file}"; then
  output::error "Error downloading the firmware"
  exit 1
fi

if [[ -f "${tmp_file}" ]]; then
  wally-cli "${tmp_file}"
fi
rm "${tmp_file}"

output::solution "Done!"
