#!/usr/bin/env bash

set -euo pipefail

[[ -z "$DOTLY_PATH" ]] && exit 1

#shellcheck source=/dev/null
. "$DOTLY_PATH/scripts/core/_main.sh"

##? Cleanup mac system. WARNING! First export your current packages!
##? 
##?
##? Usage:
##?   cleanup [-h | --help]
##?   cleanup [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot mac cleanup"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

# Here begin your script

# View:
# https://github.com/drduh/macOS-Security-and-Privacy-Guide#metadata-and-artifacts

case ${1-} in
# Any subcommand should be here
*)
  exit 1
  ;;
esac
