#!/usr/bin/env bash

set -euo pipefail

[[ -z "$DOTLY_PATH" ]] && exit 1

#shellcheck source=/dev/null
. "$DOTLY_PATH/scripts/core/_main.sh"

##? Change the columns or rows in the springboard
##?
##?
##? Usage:
##?   springboard [-h | --help]
##?   springboard [-v | --version]
##?   springboard columns <number>
##?   springboard rows <number>
##?   springboard --reset [columns|rows]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot mac springboard"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

# Here begin your script

case ${1-} in
  "columns")
    if [[ ${number:-0} -lt 1 ]]; then
      exit 1
    fi
    defaults write com.apple.dock springboard-columns -int "$number"
    ;;
  "rows")
    if [[ ${number:-0} -lt 1 ]]; then
      exit 1
    fi
    defaults write com.apple.dock springboard-rows -int "$number"
    ;;
  *)
    if ! ${reset:-}; then
      "$0" --help
      exit 1
    fi

    case "$2" in
      columns)
        defaults delete com.apple.dock springboard-columns
        ;;
      rows)
        defaults delete com.apple.dock springboard-rows
        ;;
      *)
        output::error "Something went terribly wrong"
        open "https://www.youtube.com/watch?v=t3otBjVZzT0"
        exit 1
        ;;
    esac
    ;;
esac

defaults write com.apple.dock ResetLaunchPad -bool TRUE && killall Dock
