#!/usr/bin/env bash
##? Basic script to check load time for new way of loading scripts in .Sloth
##?
##?
##? Usage:
##?   sloth [-h | --help]
##?   sloth [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
##? SCRIPT_VERSION "1.0.0"

case ${1:-} in
  # Any subcommand should be here
  *)
    output::error "Exit with error: no content yet"
    exit 1
    ;;
esac
