#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTFILES_PATH/scripts/secrets/src/secrets_files_helpers.sh"

gitkeep() {
  mkdir -p "$DOTFILES_PATH/$DOTLY_SECRETS_MODULE_PATH/$1"
  touch "$DOTFILES_PATH/$DOTLY_SECRETS_MODULE_PATH/$1/.gitkeep"
}

purge_files() {
  output::answer "📁 Removing files"
  secrets::find --exclude files | while read -r item; do
    secrets::check_exists "files/$item" >/dev/null 2>&1 && secrets::remove_file "files/$item"
  done
  secrets::purge_secrets_json
  gitkeep "files"
}

purge_vars() {
  output::answer "λ Removing vars"
  secrets::find --exclude vars | while read -r item; do
    secrets::check_exists "vars/$item" >/dev/null 2>&1 && secrets::remove_file "vars/$item"
  done
  gitkeep "vars"
}

##? Purge all vars and files files
##? 
##?
##? Usage:
##?   purge [-h | --help]
##?   purge [-v | --version]
##?   purge [files|vars] [-n | --no-sync] [-y | --yes] [-f | --force]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -f --force    No question about if you are sure... Use this option only if
##?                 you are brave enough
##?   -n --no-sync  Do not sync changes. This option ignore --yes because
##?                 sync command won't be executed.
##?   -y --yes      No prompt about if you are sure you want to sync your
##?                 secrets repository.
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets purge"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

output::empty_line
output::error "WARNING"
output::empty_line
output::error "This could be dangerous you will delete without the possibility of restoration."
output::error "It is recommended to use --no-sync option and later when you are sure you do"
output::error "not want your files do the sync manually."
output::empty_line

if ! $force; then
  output::yesno "Do you still want to continue" "N" || {
    output::error "User aborted"
    exit 1
  }
  
  output::empty_line
fi

output::header "🗑 Purging"

output::answer "Applying revert of your secrets before purge"
"$DOTLY_PATH/bin/dot" secrets apply revert

case "$1" in
"vars")
  purge_vars
  ;;
"files")
  purge_files
  ;;
*)
  purge_vars
  purge_files
  ;;
esac

if ! $no_sync; then
  if $yes; then
    "$DOTLY_PATH/bin/dot" secrets sync --yes
  else
    "$DOTLY_PATH/bin/dot" secrets sync
  fi
fi
